name: python unit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: Test
      run: python3 -m unittest
